"""empty message

Revision ID: 1cecd94c48f0
Revises: 03e2218f8e76
Create Date: 2025-02-14 09:03:27.344902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cecd94c48f0'
down_revision = '03e2218f8e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
