"""empty message

Revision ID: 76896094c54f
Revises: 
Create Date: 2025-02-20 13:00:04.610420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76896094c54f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gallerie_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('home',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_title', sa.String(length=100), nullable=False),
    sa.Column('nav_title', sa.String(length=255), nullable=True),
    sa.Column('home_text', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_title')
    )
    op.create_table('news_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('can_create_user', sa.Boolean(), nullable=True),
    sa.Column('can_edit_user', sa.Boolean(), nullable=True),
    sa.Column('can_delete_user', sa.Boolean(), nullable=True),
    sa.Column('can_view_user', sa.Boolean(), nullable=True),
    sa.Column('can_create_news', sa.Boolean(), nullable=True),
    sa.Column('can_edit_news', sa.Boolean(), nullable=True),
    sa.Column('can_delete_news', sa.Boolean(), nullable=True),
    sa.Column('can_view_news', sa.Boolean(), nullable=True),
    sa.Column('can_create_gallerie', sa.Boolean(), nullable=True),
    sa.Column('can_edit_gallerie', sa.Boolean(), nullable=True),
    sa.Column('can_delete_gallerie', sa.Boolean(), nullable=True),
    sa.Column('can_view_gallerie', sa.Boolean(), nullable=True),
    sa.Column('can_create_docs', sa.Boolean(), nullable=True),
    sa.Column('can_edit_docs', sa.Boolean(), nullable=True),
    sa.Column('can_delete_docs', sa.Boolean(), nullable=True),
    sa.Column('can_view_docs', sa.Boolean(), nullable=True),
    sa.Column('can_create_docs_types', sa.Boolean(), nullable=True),
    sa.Column('can_edit_docs_types', sa.Boolean(), nullable=True),
    sa.Column('can_delete_docs_types', sa.Boolean(), nullable=True),
    sa.Column('can_view_docs_types', sa.Boolean(), nullable=True),
    sa.Column('can_create_home', sa.Boolean(), nullable=True),
    sa.Column('can_edit_home', sa.Boolean(), nullable=True),
    sa.Column('can_delete_home', sa.Boolean(), nullable=True),
    sa.Column('can_view_home', sa.Boolean(), nullable=True),
    sa.Column('can_create_role', sa.Boolean(), nullable=True),
    sa.Column('can_edit_role', sa.Boolean(), nullable=True),
    sa.Column('can_delete_role', sa.Boolean(), nullable=True),
    sa.Column('can_view_role', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('docs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('doc_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['docs_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galerie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('gallerie_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['gallerie_type_id'], ['gallerie_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('news_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['news_type_id'], ['news_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('news')
    op.drop_table('galerie')
    op.drop_table('docs')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('news_types')
    op.drop_table('home')
    op.drop_table('gallerie_types')
    op.drop_table('docs_types')
    # ### end Alembic commands ###
