"""empty message

Revision ID: ab5eee0f93d3
Revises: f2f20a4f3f23
Create Date: 2025-03-13 08:39:11.014064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5eee0f93d3'
down_revision = 'f2f20a4f3f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sobre', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sobre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
