"""empty message

Revision ID: c38ec9cdff48
Revises: 9254790bd511
Create Date: 2025-02-13 09:10:21.110321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38ec9cdff48'
down_revision = '9254790bd511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_title', sa.String(length=255), nullable=True))
        batch_op.drop_column('nav_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_text', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('nav_title')

    # ### end Alembic commands ###
