"""empty message

Revision ID: ebe83e4e2c95
Revises: 76896094c54f
Create Date: 2025-02-21 15:28:55.453696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe83e4e2c95'
down_revision = '76896094c54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sobre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('conteudo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.drop_table('home')
    with op.batch_alter_table('galerie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_create_news_types', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_edit_news_types', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete_news_types', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_news_types', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_create_gallerie_types', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_edit_gallerie_types', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete_gallerie_types', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_gallerie_types', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('can_view_gallerie_types')
        batch_op.drop_column('can_delete_gallerie_types')
        batch_op.drop_column('can_edit_gallerie_types')
        batch_op.drop_column('can_create_gallerie_types')
        batch_op.drop_column('can_view_news_types')
        batch_op.drop_column('can_delete_news_types')
        batch_op.drop_column('can_edit_news_types')
        batch_op.drop_column('can_create_news_types')

    with op.batch_alter_table('galerie', schema=None) as batch_op:
        batch_op.drop_column('content')

    op.create_table('home',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('page_title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nav_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('home_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('path', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_title')
    )
    op.drop_table('sobre')
    # ### end Alembic commands ###
